from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol, runtime_checkable


@runtime_checkable
class ToolRegistryProtocol(Protocol):
    def get_tool(self, name: str) -> Any | None: ...

    def list_tools(self) -> list[Any]: ...

    def register(
        self,
        tool: Any,
        direct_handler: Callable[..., Awaitable[Any]] | None = None,
    ) -> None: ...

    def unregister(self, name: str) -> None: ...

    def get(self, name: str) -> Any | None: ...

    def has(self, name: str) -> bool: ...

    def get_direct_handler(self, name: str) -> Callable[..., Awaitable[Any]] | None: ...

    def get_definitions(self) -> list[dict[str, Any]]: ...

    async def execute(self, name: str, params: Any, context_obj: Any = None) -> str: ...

    @property
    def tool_names(self) -> list[str]: ...

    @property
    def direct_route_names(self) -> list[str]: ...
